server:
  port: 8082

spring:
  application:
    name: fds-detection-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8761}
  cloud:
    config:
      username: ${CONFIG_USERNAME:config}
      password: ${CONFIG_PASSWORD}
