server:
  port: 8090

spring:
  application:
    name: fds-generator
  config:
    import: configserver:http://localhost:8761
  cloud:
    config:
      username: ${CONFIG_USERNAME:config}
      password: ${CONFIG_PASSWORD:config-secret}
