server:
  port: 8083

spring:
  application:
    name: fds-alert-service
  config:
    import: configserver:http://localhost:8761
  cloud:
    config:
      username: ${CONFIG_USERNAME:config}
      password: ${CONFIG_PASSWORD:config-secret}
